#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "BioGustav"
email = "65023470+BioGustav@users.noreply.github.com"

[ui]
default-command = "log"

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[git]
sign-on-push = true