import = ["~/.config/alacritty/themes/breeze.toml"]

live_config_reload = true

[font]
    builtin_box_drawing = true
    size = 12

    [font.normal]
    family = "Roboto Mono Nerd Font Mono"
    style = "Regular"

    [font.bold]
    family = "Roboto Mono Nerd Font Mono"
    style = "Bold"

    [font.italic]
    family = "Roboto Mono Nerd Font Mono"

    [font.offset]
    x = 0
    y = 0

#[colors]
    #draw_bold_text_with_bright_colors = true

    #[colors.primary]
    #foreground = "#c5c8c6"
    #background = "#1d2021"

[env]
    TERM = "alacritty"

[shell]
    program = "/bin/zsh"

[window]
    opacity = 0.85
    decorations = "full"
    dynamic_title = true
    #startup_mode = "Maximized"

    [window.dimensions]
    columns = 130
    lines = 35

[selection]
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"
